#!/usr/bin/env python3
"""Generated by Frontend Agent - 2026-03-31T02:00:03.940278"""
import json
from pathlib import Path
from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles

app = FastAPI(title="投研知识库", version="1.0")

@app.get("/health")
async def health():
    return {"status": "OK"}

WORKSPACE = Path("/home/mickey/.openclaw/mihua")
DD_DIR = WORKSPACE / "knowledge_base_dd"
INDEX_FILE = DD_DIR / "index.json"
QUERY_UI_DIR = Path("/home/mickey/.openclaw/mihua/tools/query_ui")

_index_cache = None
def get_index():
    global _index_cache
    if _index_cache is None and INDEX_FILE.exists():
        with open(INDEX_FILE, 'r', encoding='utf-8') as f:
            _index_cache = json.load(f)
    return _index_cache or {}

templates = Jinja2Templates(directory=str(QUERY_UI_DIR / "templates"))
app.mount("/static", StaticFiles(directory=str(QUERY_UI_DIR / "static")), name="static")

# ============ API 路由 ============

@app.get("/api/companies")
async def api_companies(page: int = 1, page_size: int = 100):
    """公司列表（分页）"""
    index = get_index()
    all_companies = index.get("companies", [])
    start = (page - 1) * page_size
    end = start + page_size
    return {
        "total": len(all_companies),
        "page": page,
        "page_size": page_size,
        "companies": all_companies[start:end]
    }

@app.get("/api/company/{company_id}")
async def api_company_detail(company_id: str):
    """公司详情"""
    profile_path = DD_DIR / "companies" / company_id / "profile.json"
    if not profile_path.exists():
        raise HTTPException(status_code=404, detail="Company not found")
    try:
        with open(profile_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except json.JSONDecodeError:
        raise HTTPException(status_code=500, detail="Invalid company data")

@app.get("/api/investors")
async def api_investors():
    """投资机构列表"""
    index = get_index()
    return index.get("investors", [])

@app.get("/api/investor/{investor_id}")
async def api_investor_detail(investor_id: str):
    """机构详情"""
    investors = get_index().get("investors", [])
    for inv in investors:
        if inv.get("id") == investor_id:
            return inv
    raise HTTPException(status_code=404, detail="Investor not found")

@app.get("/api/investments")
async def api_investments():
    """投资交易列表"""
    index = get_index()
    return index.get("investments", [])

@app.get("/api/stats")
async def api_stats():
    """统计信息"""
    index = get_index()
    return {
        "total_companies": len(index.get("companies", [])),
        "total_investors": len(index.get("investors", [])),
        "total_investments": len(index.get("investments", [])),
        "last_updated": index.get("metadata", {}).get("generated_at")
    }

@app.get("/company/{company_id}")

@app.get("/company/{company_id}")
async def company_detail(request: Request, company_id: str):
    """公司详情页（使用简化模板，确保稳定）"""
    profile_path = DD_DIR / "companies" / company_id / "profile.json"
    if not profile_path.exists():
        raise HTTPException(status_code=404, detail="Company not found")
    try:
        with open(profile_path, 'r', encoding='utf-8') as f:
            company = json.load(f)
    except json.JSONDecodeError:
        raise HTTPException(status_code=500, detail="Invalid company data")
    
    return templates.TemplateResponse("company_detail_simple.html", {
        "request": request,
        "company": company
    })

async def company_detail(request: Request, company_id: str):
    """公司详情页（HTML 模板）"""
    profile_path = DD_DIR / "companies" / company_id / "profile.json"
    if not profile_path.exists():
        raise HTTPException(status_code=404, detail="Company not found")
    try:
        with open(profile_path, 'r', encoding='utf-8') as f:
            company = json.load(f)
    except json.JSONDecodeError:
        raise HTTPException(status_code=500, detail="Invalid company data")
    
@app.get("/company/{company_id}")
async def company_detail(request: Request, company_id: str):
    """公司详情页（简化版模板）"""
    profile_path = DD_DIR / "companies" / company_id / "profile.json"
    if not profile_path.exists():
        raise HTTPException(status_code=404, detail="Company not found")
    
    try:
        with open(profile_path, 'r', encoding='utf-8') as f:
            company = json.load(f)
    except json.JSONDecodeError:
        raise HTTPException(status_code=500, detail="Invalid company data")
    
    # 使用简化模板（更健壮，变量少）
    return templates.TemplateResponse("company_detail_simple.html", {
        "request": request,
        "company": company,
    })


@app.get("/investors")
async def investors_page(request: Request):
    """投资机构列表页"""
    index = get_index()
    investors = index.get("investors", [])
    return templates.TemplateResponse("investors.html", {
        "request": request,
        "investors": investors
    })

@app.get("/investor/{investor_id}")
async def investor_detail(request: Request, investor_id: str):
    """机构详情页"""
    investors = get_index().get("investors", [])
    for inv in investors:
        if inv.get("id") == investor_id:
            return templates.TemplateResponse("investor_detail.html", {
                "request": request,
                "investor": inv
            })
    raise HTTPException(status_code=404, detail="Investor not found")

@app.get("/investments")
async def investments_page(request: Request):
    """投资交易列表页"""
    index = get_index()
    investments = index.get("investments", [])
    return templates.TemplateResponse("investments.html", {
        "request": request,
        "investments": investments
    })

@app.get("/investment/{investment_id}")
async def investment_detail(request: Request, investment_id: str):
    """交易详情页（简化：返回 JSON）"""
    investments = get_index().get("investments", [])
    for inv in investments:
        if inv.get("id") == investment_id:
            return inv
    raise HTTPException(status_code=404, detail="Investment not found")

@app.get("/search")
async def search_page(request: Request, q: str = None):
    """搜索页面"""
    if not q:
        return templates.TemplateResponse("search_results.html", {
            "request": request,
            "query": "",
            "results": []
        })
    
    # 简单搜索逻辑
    index = get_index()
    results = []
    q_lower = q.lower()
    
    # 搜索公司
    for c in index.get("companies", []):
        if q_lower in c.get("name", "").lower() or q_lower in c.get("english_name", "").lower():
            results.append({"type": "company", "data": c})
    
    # 搜索机构
    for inv in index.get("investors", []):
        if q_lower in inv.get("name", "").lower():
            results.append({"type": "investor", "data": inv})
    
    return templates.TemplateResponse("search_results.html", {
        "request": request,
        "query": q,
        "results": results
    })

@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    """首页"""
    index = get_index()
    if not index or "metadata" not in index:
        # 强制重新加载
        with open(INDEX_FILE, 'r', encoding='utf-8') as f:
            index = json.load(f)
            _index_cache = index
    
    recent = sorted(index.get("investments", []), key=lambda x: x.get("date", ""), reverse=True)[:10]
    # 完整度高的公司
    def is_complete(comp):
        profile_file = DD_DIR / "companies" / comp["id"] / "profile.json"
        if not profile_file.exists():
            return False
        try:
            data = json.loads(profile_file.read_text(encoding='utf-8'))
            has_industry = data.get("profile", {}).get("industry")
            has_financials = data.get("financials")
            has_thesis = any(k in data for k in ["investment_thesis", "investment_analysis", "recommendation", "investment_recommendation"])
            return has_industry and (has_financials or has_thesis)
        except:
            return False
    
    complete_companies = [c for c in index.get("companies", []) if is_complete(c)][:10]
    return templates.TemplateResponse("index.html", {
        "request": request,
        "index_meta": index.get("metadata", {}),
        "recent_investments": recent,
        "complete_companies": complete_companies
    })
